# To load local files to minikube 
#minikube mount /home/ingeniero/Documents/gitRepository/udemy/k6/project-final-kubernates-v001/shared/server-mock:/mnt/files
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mockserver
  name: mockserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mockserver
  template:
    metadata:
      labels:
        app: mockserver
    spec:
      containers:
      - image: mocksserver/main
        name: mockserver
        ports:
        - containerPort: 3100
        - containerPort: 3110
        env:
          - name: MOCKS_PATH
            value: /input
        command: ["npm", "start"]
        volumeMounts:
        - name: mocks-volume-1
          mountPath: /input
      volumes:
        - name: mocks-volume-1
          hostPath: 
            path: /mnt/files
            type: Directory
      
---
apiVersion: v1
kind: Service
metadata:
  name: mockserver
spec:
  ports:
  - name: http
    port: 3100
    protocol: TCP
    targetPort: 3100
  - name: https
    port: 3110
    protocol: TCP
    targetPort: 3110
  selector:
    app: mockserver
  type: LoadBalancer
