apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: dr-msvc-backend-bff-service
  namespace: default
spec:
  host: msvc-backend-bff-service
  subsets:
    # - name: safe
    #   labels:
    #     version: v1
    # - name: risky
    #   labels:
    #     version: v2
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 7         
      interval: 10s                   
      baseEjectionTime: 30s           
      maxEjectionPercent: 50          
      minHealthPercent: 50            

