apiVersion: v1
kind: Pod
metadata:
  name: ejemplo-pod
spec:
  containers:
  - name: ejemplo-container
    image: nginx
    volumeMounts:
    - mountPath: "/usr/share/nginx/html"  # Carpeta en el pod
      name: ejemplo-volumen
  volumes:
  - name: ejemplo-volumen
    persistentVolumeClaim:
      claimName: ejemplo-pvc